WHITE = 1
BLACK = 0
size_of_cell = 65
coefficient = 20
length_of_divider_between_cells = 6
# типывозможгых ходов
NORMAL_MOVE = 'normal'
TAKE_MOVE = 'take'
CONVERSION_MOVE = 'conversion'
PASSED_TAKE_MOVE = 'passed_take'
CASTLING_MOVE = 'castling'
